repo: https://github.com/Siflower/1806_SDK.git
branch: release2.0.0
git_clone_dir: openwrt-18.06/siflower
openwrt_root_dir: openwrt-18.06/siflower/openwrt-18.06
revision: d5ea38755b859ba4c6910036e2ea6bb6888a932b

patch_folders:
  - patches-siflower-18.x/
